export const FETCH_PRODUCTS_PAGINATION_REQUEST = 'FETCH_PRODUCTS_PAGINATION_REQUEST';
export const FETCH_PRODUCTS_PAGINATION_REQUEST_SUCCESS = 'FETCH_PRODUCTS_PAGINATION_REQUEST_SUCCESS';
export const FETCH_PRODUCTS_PAGINATION_REQUEST_FAIL = 'FETCH_PRODUCTS_PAGINATION_REQUEST_FAIL';

export const FETCH_CATEGORIES_REQUEST = 'FETCH_CATEGORIES_REQUEST';
export const FETCH_CATEGORIES_REQUEST_SUCCESS = 'FETCH_CATEGORIES_REQUEST_SUCCESS';
export const FETCH_CATEGORIES_REQUEST_FAIL = 'FETCH_CATEGORIES_REQUEST_FAIL';